# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import iPhone as file1
import laptops as file2

class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(773, 571)
        self.centralwidget = QtWidgets.QWidget(login_window)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 9, 751, 551))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 0, 751, 541))
        self.label.setStyleSheet("\n"
"border-image: url(95-951162_black-aesthetic-wallpaper-laptop.jpg);\n"
"border top-left radius: 60px")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(360, 30, 371, 341))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(240,240,240,240)\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(370, 60, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Lato Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setGeometry(QtCore.QRect(460, 50, 256, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(390, 130, 281, 20))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.laptop_btn = QtWidgets.QPushButton(self.widget)
        self.laptop_btn.setGeometry(QtCore.QRect(410, 230, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.laptop_btn.setFont(font)
        self.laptop_btn.setStyleSheet("background-color: rgb(91, 91, 91);\n"
"background-color: rgb(193, 193, 193);")
        self.laptop_btn.setObjectName("laptop_btn")
        self.iphone_btn = QtWidgets.QPushButton(self.widget)
        self.iphone_btn.setGeometry(QtCore.QRect(630, 230, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.iphone_btn.setFont(font)
        self.iphone_btn.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.iphone_btn.setObjectName("iphone_btn")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(670, 370, 691, 571))
        self.label_5.setStyleSheet("background-image: url(:/images/P-638079-u9e2a6JrTf-1.jpg);\n"
"border-color: rgb(198, 198, 198);\n"
"border-image: url(:/images/P-638079-u9e2a6JrTf-1.jpg);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        login_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(login_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 773, 21))
        self.menubar.setObjectName("menubar")
        login_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(login_window)
        self.statusbar.setObjectName("statusbar")
        login_window.setStatusBar(self.statusbar)
        self.iphone_btn.clicked.connect(self.show_iphone)
        # self.iphone_btn.clicked.connect(iphone_window.close)
        self.iphone_btn.clicked.connect(self.show_laptop)
        self.retranslateUi(login_window)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "MainWindow"))
        self.label_3.setText(_translate("login_window", "Enter URL"))
        self.label_4.setText(_translate("login_window", "             Select Category"))
        self.laptop_btn.setText(_translate("login_window", "Laptops"))
        self.iphone_btn.setText(_translate("login_window", "iPhone"))
    def show_iphone(self):
        self.window= QtWidgets.QWidget()
        self.ui=file1.Ui_iphone_window()
        self.ui.setupUi(self.window)
        self.window.show()
    def show_laptop(self):
        self.window= QtWidgets.QWidget()
        self.ui=file2.Ui_Laptop_window()
        self.ui.setupUi(self.window)
        self.window.show()    

# import form1_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_window = QtWidgets.QMainWindow()
    ui = Ui_login_window()
    ui.setupUi(login_window)
    login_window.show()
    sys.exit(app.exec_())
